#!/usr/bin/env python3
"""Prepare an Autotools VMOD source tree for the selected engine.

For a cross-family build, rewrite the known API names from the source family to
the target family (DESIGN.md decision 19). Every build also replaces legacy
``varnish_vsc`` directives with ``vinyl_vsc``, the only form recognized by the
vsctool shared by both engines (decision 28).
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import Counter
from pathlib import Path


FAMILIES = ("vinyl", "varnish")
VSC_DIRECTIVES_MARKER = "vsc-directives"

# Cross-family builds targeting Vinyl cannot use one fixed private-header name:
# supported Vinyl engines expose different names without a compatibility alias.
VINYL_PRIVATE_HEADERS = ("cache_vinyld.h", "cache_int.h")
DEFAULT_VINYL_PRIVATE_HEADER = "cache_vinyld.h"
VARNISH_PRIVATE_HEADER = "cache_varnishd.h"

VTC_TEST_TOOL_SPELLINGS = (b"vinyltest", b"varnishtest")

Replacement = tuple[bytes, bytes]


def _header_macro(name: str) -> bytes:
    """Match the guard generated by Autoconf's AC_CHECK_HEADERS check."""
    return name.upper().replace(".", "_").encode()


def _private_header_replacements(vinyl_header: str) -> tuple[Replacement, ...]:
    return (
        (vinyl_header.encode(), VARNISH_PRIVATE_HEADER.encode()),
        (_header_macro(vinyl_header), _header_macro(VARNISH_PRIVATE_HEADER)),
    )


VINYL_TO_VARNISH: tuple[Replacement, ...] = (
    # queryfilter's m4 uses the bare [VINYL] prefix, so its Makefile consumes
    # VINYL_CFLAGS. The VINYL_ rule renames that consumer; without this row
    # the macro keeps defining the old name and the include path goes empty.
    (b"PKG_CHECK_MODULES([VINYL]", b"PKG_CHECK_MODULES([VARNISH]"),
    (b"VINYLAPI", b"VARNISHAPI"),
    (b"VINYLSRC", b"VARNISHSRC"),
    (b"VINYLTEST", b"VARNISHTEST"),
    (b"VINYLD", b"VARNISHD"),
    (b"VINYL_", b"VARNISH_"),
    (b"vinylapi", b"varnishapi"),
    (b"vinyltest", b"varnishtest"),
    (b"vinyld", b"varnishd"),
    (b"vinyladm", b"varnishadm"),
    (b"vinylstat", b"varnishstat"),
    (b"vinyl-cache/", b"varnish/"),
    (b"/vinyl/", b"/varnish/"),
)

# This preparation applies even when no family translation is needed: the
# shared vsctool silently ignores varnish_vsc and emits no counter headers.
VSC_REPLACEMENT: Replacement = (b"varnish_vsc", b"vinyl_vsc")


def replacements(
    source_family: str,
    target_family: str,
    vinyl_private_header: str = DEFAULT_VINYL_PRIVATE_HEADER,
) -> tuple[Replacement, ...]:
    """Return the ordered cross-family replacements, or none when the families match.

    When targeting Vinyl, the private-header replacement must precede the
    generic daemon-name replacement. Otherwise cache_varnishd.h becomes
    cache_vinyld.h even when the selected engine requires cache_int.h. When
    targeting Varnish, both Vinyl spellings map to its single header name.
    """
    if vinyl_private_header not in VINYL_PRIVATE_HEADERS:
        raise ValueError(f"unknown Vinyl private header spelling: {vinyl_private_header}")
    if source_family == target_family:
        return ()
    if (source_family, target_family) == ("vinyl", "varnish"):
        headers: tuple[Replacement, ...] = ()
        for name in VINYL_PRIVATE_HEADERS:
            headers += _private_header_replacements(name)
        return headers + VINYL_TO_VARNISH
    if (source_family, target_family) == ("varnish", "vinyl"):
        directional_replacements = _private_header_replacements(vinyl_private_header) + VINYL_TO_VARNISH
        return tuple((new, old) for old, new in directional_replacements)
    raise ValueError(f"unsupported family normalization: {source_family} -> {target_family}")


def _substitute(data: bytes, old: bytes, new: bytes, counts: Counter[str]) -> bytes:
    count = data.count(old)
    if count:
        counts[f"{old.decode()} -> {new.decode()}"] += count
        return data.replace(old, new)
    return data


def normalize_bytes(
    data: bytes,
    path: Path,
    source_family: str,
    target_family: str,
    family_replacements: tuple[Replacement, ...],
) -> tuple[bytes, Counter[str]]:
    counts: Counter[str] = Counter()
    if path.suffix == ".vsc":
        data = _substitute(data, *VSC_REPLACEMENT, counts)
    for old, new in family_replacements:
        # vtest2's leading keyword is independent of the engine family, so a
        # cross-family tool-name replacement would produce invalid VTC syntax.
        if path.suffix == ".vtc" and old in VTC_TEST_TOOL_SPELLINGS:
            continue
        data = _substitute(data, old, new, counts)

    if path.suffix == ".vtc" and source_family != target_family:
        # A bare family name is a command in VTC syntax but can be ordinary
        # prose elsewhere, so this replacement is confined to whole VTC words.
        command = re.compile(rb"\b" + source_family.encode() + rb"\b")
        data, count = command.subn(target_family.encode(), data)
        if count:
            counts[f"VTC command {source_family} -> {target_family}"] += count
        # Some Vinyl sources use vinyltest despite vtest2 requiring varnishtest
        # or vtest here; canonicalize that header in either direction.
        data, count = re.subn(rb"(?m)^vinyltest(?=\s|$)", b"varnishtest", data)
        if count:
            counts["VTC header vinyltest -> varnishtest"] += count
    return data, counts


def normalize_tree(
    root: Path,
    source_family: str,
    target_family: str,
    vinyl_private_header: str = DEFAULT_VINYL_PRIVATE_HEADER,
) -> tuple[list[tuple[Path, Counter[str]]], Counter[str]]:
    changed: list[tuple[Path, Counter[str]]] = []
    totals: Counter[str] = Counter()
    same_family = source_family == target_family
    family_replacements = replacements(source_family, target_family, vinyl_private_header)
    for directory, names, filenames in os.walk(root):
        names[:] = sorted(name for name in names if name != ".git")
        for filename in sorted(filenames):
            path = Path(directory, filename)
            if path.is_symlink():
                continue
            if same_family and path.suffix != ".vsc":
                continue
            data = path.read_bytes()
            if b"\0" in data:
                continue
            normalized, counts = normalize_bytes(
                data, path, source_family, target_family, family_replacements
            )
            if not counts:
                continue
            path.write_bytes(normalized)
            changed.append((path.relative_to(root), counts))
            totals.update(counts)
    return changed, totals


def normalization_name(source_family: str, target_family: str) -> str:
    if source_family == target_family:
        return VSC_DIRECTIVES_MARKER
    return f"{source_family}-to-{target_family}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-family", required=True, choices=FAMILIES)
    parser.add_argument("--target-family", required=True, choices=FAMILIES)
    parser.add_argument("--vinyl-private-header", default=DEFAULT_VINYL_PRIVATE_HEADER,
                        choices=VINYL_PRIVATE_HEADERS,
                        help="the daemon-private header name the Vinyl engine installs under cache/")
    parser.add_argument("--marker", type=Path,
                        help="write the normalization name here when any file changed")
    parser.add_argument("source", type=Path)
    args = parser.parse_args(argv)

    if not args.source.is_dir():
        parser.error(f"source tree is not a directory: {args.source}")

    changed, totals = normalize_tree(args.source, args.source_family, args.target_family,
                                     args.vinyl_private_header)
    same_family = args.source_family == args.target_family
    if not changed:
        if same_family:
            print("no legacy VSC directive spellings found; source left untouched")
            return 0
        # Finding none of the declared source family's spellings points to a
        # stale catalog entry; recording a successful normalization would lie.
        print(
            f"no {args.source_family} API spellings found while normalizing for {args.target_family}",
            file=sys.stderr,
        )
        return 1

    name = normalization_name(args.source_family, args.target_family)
    if args.marker is not None:
        args.marker.write_text(name + "\n", encoding="utf-8")
    if same_family:
        print(f"normalized VSC directives in {len(changed)} files ({name})")
    else:
        print(f"normalized {args.source_family} VMOD source for {args.target_family} in {len(changed)} files")
    for path, counts in changed:
        detail = ", ".join(f"{name}: {count}" for name, count in sorted(counts.items()))
        print(f"  {path}: {detail}")
    print("totals:")
    for name, count in sorted(totals.items()):
        print(f"  {name}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
