#!/bin/bash
#
# Assemble the canonical pinned Vinyl source archive and both Debian orig
# tarballs. Runs in the buildroot image so that the tar implementation, and
# therefore the digest, does not depend on the developer's laptop.
set -euo pipefail
export LC_ALL=C

commit=$VINYL_GIT_COMMIT
uv=$VINYL_UPSTREAM_VERSION
epoch=$VINYL_SOURCE_DATE_EPOCH
source_kind=${VINYL_SOURCE_KIND:-git}

case $source_kind in
tarball)
	# Drafted 2026-07-26, unexecuted until the first release-track run.
	# The upstream tarball IS the orig tarball: no splice, no generated
	# include/vcs_version.h or include/vmod_abi.h to synthesise, because a
	# full dist archive already ships them baked from the tagged release.
	echo "===== verifying the upstream Vinyl tarball (release track) ====="
	src=/work/vinyl-cache-$uv.tgz
	got=$(sha256sum "$src" | awk '{print $1}')
	echo "sha256: $got"
	if [ "$got" != "$VINYL_SOURCE_SHA256" ]; then
		echo "E: upstream tarball digest $got != pinned $VINYL_SOURCE_SHA256" >&2
		exit 1
	fi
	echo "OK: upstream tarball digest matches the pinned value (defence in depth; build.sh already checked this on the host)"

	# Renaming a .tgz to Debian's *_orig.tar.gz convention is fine for
	# dpkg: it only cares about the .orig.tar.<ext> suffix, and gzip is
	# gzip regardless of what the upstream project called the extension.
	cp "$src" "/work/build/vinyl-cache_$uv.orig.tar.gz"

	echo "===== asserting the baked strict VMOD ABI string ====="
	got=$(tar -xzO -f "$src" "vinyl-cache-$uv/include/vmod_abi.h" |
		sed -n 's/^#define VMOD_ABI_Version "\(.*\)"$/\1/p')
	echo "baked VMOD_ABI_Version: [$got]"
	if [ "$got" != "$VINYL_ABI_STRING" ]; then
		echo "E: baked ABI string does not match the pinned value [$VINYL_ABI_STRING]" >&2
		exit 1
	fi
	echo "OK: baked strict VMOD ABI string matches the pinned value"
	;;
git)
	echo "===== canonical pinned Vinyl source archive ====="
	rm -rf /tmp/pin
	mkdir -p /tmp/pin
	for t in /work/pin/*.tar; do
		echo "splicing $t"
		tar -C /tmp/pin -xf "$t"
	done
	tar --format=gnu --sort=name --owner=0 --group=0 --numeric-owner \
		--mtime="@$epoch" \
		-C /tmp/pin -cf "/work/vinyl-source-$commit.tar" vinyl-src
	sha256sum "/work/vinyl-source-$commit.tar"

	echo "===== deriving the Vinyl orig tarball ====="
	rm -rf /tmp/orig
	mkdir -p /tmp/orig
	tar -C /tmp/orig -xf "/work/vinyl-source-$commit.tar"
	mv /tmp/orig/vinyl-src "/tmp/orig/vinyl-cache-$uv"
	d=/tmp/orig/vinyl-cache-$uv

	# include/vcs_version.h and include/vmod_abi.h are generated by
	# include/generate.py from the Git checkout, and are therefore absent from a
	# git-archive export. A release tarball is expected to contain them:
	# include/Makefile.am regenerates them only when a .git directory is present
	# or when they are missing, so shipping them here is what stops the build from
	# baking the string "NOGIT" into the strict VMOD ABI.
	#
	# PACKAGE_STRING is derived from the exported configure.ac rather than assumed,
	# and the resulting ABI string is asserted against the pinned value.
	pkg_name=$(sed -n 's/^AC_INIT(\[\([^]]*\)\], *\[\([^]]*\)\].*/\1/p' "$d/configure.ac")
	pkg_ver=$(sed -n 's/^AC_INIT(\[\([^]]*\)\], *\[\([^]]*\)\].*/\2/p' "$d/configure.ac")
	pkg_string="$pkg_name $pkg_ver"
	echo "PACKAGE_STRING from configure.ac: [$pkg_string]"

	cat > "$d/include/vcs_version.h" <<EOF
/* $commit */
/*
 * NB:  This file is machine generated, DO NOT EDIT!
 *
 * Edit and run include/generate.py instead.
 */

#define VCS_Version "$commit"
EOF

	cat > "$d/include/vmod_abi.h" <<EOF
/*
 * NB:  This file is machine generated, DO NOT EDIT!
 *
 * Edit and run include/generate.py instead.
 */

#define VMOD_ABI_Version "$pkg_string $commit"
EOF

	got=$(sed -n 's/^#define VMOD_ABI_Version "\(.*\)"$/\1/p' "$d/include/vmod_abi.h")
	echo "generated VMOD_ABI_Version: [$got]"
	if [ "$got" != "$VINYL_ABI_STRING" ]; then
		echo "E: generated ABI string does not match the pinned value [$VINYL_ABI_STRING]" >&2
		exit 1
	fi
	echo "OK: generated strict VMOD ABI string matches the pinned value"

	touch -d "@$epoch" "$d/include/vcs_version.h" "$d/include/vmod_abi.h"
	tar --format=gnu --sort=name --owner=0 --group=0 --numeric-owner \
		--mtime="@$epoch" \
		-C /tmp/orig -cf - "vinyl-cache-$uv" | gzip -9n > "/work/build/vinyl-cache_$uv.orig.tar.gz"
	sha256sum "/work/build/vinyl-cache_$uv.orig.tar.gz"
	;;
*)
	echo "E: unknown VINYL_SOURCE_KIND '$source_kind' (git|tarball)" >&2
	exit 1
	;;
esac

echo "===== unpacking both source trees for dpkg-buildpackage ====="
rm -rf "/work/build/vinyl-cache-$uv"
tar -C /work/build -xf "/work/build/vinyl-cache_$uv.orig.tar.gz"
cp -R /work/vinyl-debian "/work/build/vinyl-cache-$uv/debian"
chmod 0755 "/work/build/vinyl-cache-$uv/debian/rules" \
	"/work/build/vinyl-cache-$uv/debian/vinylreload" \
	"/work/build/vinyl-cache-$uv/debian/vinyl-cache.postinst" \
	"/work/build/vinyl-cache-$uv/debian/vinyl-cache.postrm"

rm -rf "/work/build/libvmod-cachetag-$CACHETAG_VERSION"
tar -C /work/build -xf "/work/build/libvmod-cachetag_$CACHETAG_VERSION.orig.tar.gz"
cp -R /work/cachetag-debian "/work/build/libvmod-cachetag-$CACHETAG_VERSION/debian"
chmod 0755 "/work/build/libvmod-cachetag-$CACHETAG_VERSION/debian/rules"

ls -la /work/build
echo "===== assemble-source complete ====="
