#!/bin/sh

set -e

case "$1" in
        upgrade)
        ;;

        remove|failed-upgrade|abort-install|abort-upgrade|disappear)

        if dpkg-statoverride --list /var/log/vinyl-cache >/dev/null; then
            dpkg-statoverride --remove /var/log/vinyl-cache || true

        fi

        if test -e /var/log/vinyl-cache ; then

            rm -r /var/log/vinyl-cache > /dev/null 2>&1 || exit 78

        fi

        if test -e /var/lib/vinyl-cache; then

                rm -r /var/lib/vinyl-cache > /dev/null 2>&1 || exit 78
        fi

        ;;

        purge)

        if test -e /var/log/vinyl-cache; then

                rm -r /var/log/vinyl-cache > /dev/null 2>&1 || exit 78

        fi

        if test -e /var/lib/vinyl-cache; then

                rm -r /var/lib/vinyl-cache > /dev/null 2>&1 || exit 78
        fi

        dpkg-statoverride --remove /var/log/vinyl-cache || true

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 64

esac

#DEBHELPER#

exit 0
